config/routes.rb
Rails.application.routes.draw do
  resources :service_types
  resources :parcels
  resources :addresses
  resources :users
  root to: 'parcels#index'
  get '/search', to: 'search#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/parcel.rb
class Parcel < ApplicationRecord

	STATUS = ['Sent', 'In Transit', 'Delivered']
	PAYMENT_MODE = ['COD', 'Prepaid']

	validates :weight, :status, presence: true
	validates :status, inclusion: STATUS
	validates :payment_mode, inclusion: PAYMENT_MODE

	belongs_to :service_type
	belongs_to :sender, class_name: 'User'
	belongs_to :receiver, class_name: 'User'

	after_create :send_notification

	private

	def send_notification
		UserMailer.with(parcel: self).status_email.deliver_later
	end

end

app/controllers/parcels_controller.rb
class ParcelsController < ApplicationController
  before_action :set_parcel, only: %i[ show edit update destroy ]

  # GET /parcels or /parcels.json
  def index
    @parcels = Parcel.all
  end

  # GET /parcels/1 or /parcels/1.json
  def show
  end

  # GET /parcels/new
  def new
    @parcel = Parcel.new
    @users = User.all.map{|user| [user.name_with_address, user.id]}
    @service_types = ServiceType.all.map{|service_type| [service_type.name, service_type.id]}
  end

  # GET /parcels/1/edit
  def edit
    @users = User.all.map{|user| [user.name_with_address, user.id]}
    @service_types = ServiceType.all.map{|service_type| [service_type.name, service_type.id]}
  end

  # POST /parcels or /parcels.json
  def create
    @parcel = Parcel.new(parcel_params)

    respond_to do |format|
      if @parcel.save
        format.html { redirect_to @parcel, notice: 'Parcel was successfully created.' }
        format.json { render :show, status: :created, location: @parcel }
      else
        format.html do
          @users = User.all.map{|user| [user.name_with_address, user.id]}
          @service_types = ServiceType.all.map{|service_type| [service_type.name, service_type.id]} 
          render :new, status: :unprocessable_entity
        end
        format.json { render json: @parcel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parcels/1 or /parcels/1.json
  def update
    respond_to do |format|
      if @parcel.update(parcel_params)
        format.html { redirect_to @parcel, notice: 'Parcel was successfully updated.' }
        format.json { render :show, status: :ok, location: @parcel }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @parcel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parcels/1 or /parcels/1.json
  def destroy
    @parcel.destroy
    respond_to do |format|
      format.html { redirect_to parcels_url, notice: 'Parcel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parcel
      @parcel = Parcel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def parcel_params
      params.require(:parcel).permit(:weight, :status, :service_type_id,
                                     :payment_mode, :sender_id, :receiver_id,
                                     :cost)
    end
end

app/helpers/parcels_helper.rb
module ParcelsHelper
end

app/views/parcels/_form.html.erb
<%= form_with(model: parcel) do |form| %>
  <% if parcel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(parcel.errors.count, "error") %> prohibited this parcel from being saved:</h2>

      <ul>
        <% parcel.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :weight %>
    <%= form.text_field :weight %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.select :status, Parcel::STATUS %>
  </div>

  <div class="field">
    <%= form.label :service_type_id %>
    <%= form.select :service_type_id, @service_types %>
  </div>

  <div class="field">
    <%= form.label :payment_mode %>
    <%= form.select :payment_mode, Parcel::PAYMENT_MODE %>
  </div>

  <div class="field">
    <%= form.label :sender_id %>
    <%= form.select :sender_id, @users %>
    <%= link_to 'New Sender', new_user_path %>
  </div>

  <div class="field">
    <%= form.label :receiver_id %>
    <%= form.select :receiver_id, @users %>
    <%= link_to 'New Receiver', new_user_path %>
  </div>

  <div class="field">
    <%= form.label :cost %>
    <%= form.text_field :cost %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/parcels/edit.html.erb
<h1>Editing Parcel</h1>

<%= render 'form', parcel: @parcel %>

<%= link_to 'Show', @parcel %> |
<%= link_to 'Back', parcels_path %>

app/views/parcels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>List Parcels</h1>

<br />

<%= link_to 'New Parcel', new_parcel_path %>

<br /><br />

<table>
  <thead>
    <tr>
      <th>Weight</th>
      <th>Status</th>
      <th>Service Type</th>
      <th>Payment Mode</th>
      <th>Sender</th>
      <th>Receiver</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @parcels.each do |parcel| %>
      <tr>
        <td><%= parcel.weight %></td>
        <td><%= parcel.status %></td>
        <td><%= parcel.service_type.name %></td>
        <td><%= parcel.payment_mode %></td>
        <td><%= parcel.sender.name %></td>
        <td><%= parcel.receiver.name %></td>
        <td><%= link_to 'Show', parcel %></td>
        <td><%= link_to 'Edit', edit_parcel_path(parcel) %></td>
        <td><%= link_to 'Destroy', parcel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/parcels/new.html.erb
<h1>New Parcel</h1>

<%= render 'form', parcel: @parcel %>

<%= link_to 'Back', parcels_path %>

app/views/parcels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Weight:</strong>
  <%= @parcel.weight %>
</p>

<p>
  <strong>Status:</strong>
  <%= @parcel.status %>
</p>

<p>
  <strong>Service Type:</strong>
  <%= @parcel.service_type.name %>
</p>

<p>
  <strong>Payment Mode:</strong>
  <%= @parcel.payment_mode %>
</p>

<p>
  <strong>Sender:</strong>
  <%= @parcel.sender.name %>
</p>

<p>
  <strong>Receiver:</strong>
  <%= @parcel.receiver.name %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @parcel.cost %>
</p>

<%= link_to 'Edit', edit_parcel_path(@parcel) %> |
<%= link_to 'Back', parcels_path %>